### ISSUE TITLE
Bot does not send screenshot to channel under unknown circumstances

### ISSUE THREAD

**Issue by Volleo6144** [ledlamp/puppeteer-discord-bot#1]
...yeah, @ledlamp already knows this is an issue, but let's document it here
![image](https://user-images.githubusercontent.com/38385509/57575641-0a26e580-7414-11e9-8372-7b529ab18b7d.png)

**Comment by ledlamp** [comment]
late reply but fixed by evicting vistril's fatass some1bot

**Comment by Vistril** [comment]
:(
