### ISSUE TITLE
damn bot keeps going offline

### ISSUE THREAD

**Issue by ledlamp** [ledlamp/puppeteer-discord-bot#6]
![FUUU](https://cdn.discordapp.com/attachments/690034123053727819/699775186307645550/676848388599447555.gif)

**Comment by Priyanshu348** [comment]
Pls can you give your server

**Comment by ledlamp** [comment]
uhm... ACREtfp

o and apparently I forgot to close this issue with ec89c96f56ff90b7c38eac4910f8f7730caa8125
